from typing import List
from pydantic import BaseModel, Field

class Source(BaseModel):
    """Schema for the source used by agent"""
    url: str = Field(..., description="The URL of the source.")

class Answer(BaseModel):
    """Schema for the answer part of the agent's response"""
    jobPosting: str = Field(..., description="A summary of job post title found by the agent.")
    isOpenforApplication: bool = Field(..., description="Indicates there is a apply button which indicates that the job posting is open for applicants.")

class AgentResponse(BaseModel):
    """Schema for the agent's response"""
    jobPostings: List[Answer] = Field(default_factory=list, description="List of job postings generated by the agent.")
    sources: List[Source] = Field(default_factory=list, description="List of sources used to generate the answer.")